import { Completion } from "@codemirror/autocomplete";

export const zodCompletionOptions: Completion[] = [
  {
    label: ".any",
    displayLabel: "any",
    apply: '.any',
    type: 'function',
    detail: 'z.ZodAny',
  },
  {
    label: ".array",
    displayLabel: "array",
    apply: '.array',
    type: 'function',
    detail: 'z.ZodArray',
  },
  {
    label: ".boolean",
    displayLabel: "boolean",
    apply: '.boolean',
    type: 'function',
    detail: 'z.ZodBoolean',
  },
  {
    label: ".date",
    displayLabel: "date",
    apply: '.date',
    type: 'function',
    detail: 'z.ZodDate',
  },
  {
    label: ".number",
    displayLabel: "number",
    apply: '.number',
    type: 'function',
    detail: 'z.ZodNumber',
  },
  {
    label: ".string",
    displayLabel: "string",
    apply: '.string',
    type: 'function',
    detail: 'z.ZodString',
  },
  {
    label: ".object",
    displayLabel: "object",
    apply: '.object',
    type: 'function',
    detail: 'z.ZodObject',
  },
  {
    label: ".null",
    displayLabel: "null",
    apply: '.null',
    type: 'function',
    detail: 'z.ZodNull',
  },
  {
    label: ".undefined",
    displayLabel: "undefined",
    apply: '.undefined',
    type: 'function',
    detail: 'z.ZodUndefined',
  },
  {
    label: ".strict",
    displayLabel: "strict",
    apply: '.strict',
    type: 'method',
    detail: 'z.ZodObject<T, "strict", Catchall>',
  },
  {
    label: ".bigint",
    displayLabel: "bigint",
    apply: '.bigint',
    type: 'function',
    detail: 'z.ZodBigInt',
  },
  {
    label: ".enum",
    displayLabel: "enum",
    apply: '.enum',
    type: 'function',
    detail: 'z.ZodEnum',
  },
  {
    label: ".function",
    displayLabel: "function",
    apply: '.function',
    type: 'function',
    detail: 'z.ZodFunction',
  },
  {
    label: ".literal",
    displayLabel: "literal",
    apply: '.literal',
    type: 'function',
    detail: 'z.ZodLiteral',
  },
  {
    label: ".intersection",
    displayLabel: "intersection",
    apply: '.intersection',
    type: 'function',
    detail: 'z.ZodIntersection',
  },
  {
    label: ".union",
    displayLabel: "union",
    apply: '.union',
    type: 'function',
    detail: 'z.ZodUnion',
  },
];